### ISSUE TITLE
build error with Ubuntu LTS 22.04

### ISSUE THREAD

**Issue by foldfree** [werkshy/pickup#338]
`go version go1.20.5 linux/amd64`

following the instructions I run `go build` and it return `main.go:45:12: pattern react/dist: no matching files found`
If I create a blank file the project is building and run however the web server is an empty html file!

Should I make this file and what should I put in it?

**Comment by werkshy** [comment]
Hi @foldfree (wow, a user, I hadn't imagined anyone finding this project after all this time!)

The go binary embeds the (very minimal) react frontend so it can be deployed as a single executable, but it does need the frontend to have been built first. The simple Makefile automates this including installing the yarn dependencies: just run `make` in the root directory.

You will need `yarn` installed for the web dependencies - depending on which Linux distro you are on that might be in the `npm` package or maybe a separate `yarn` package.

The manual steps for this would be:
```
# (previously: install yarn)
cd react
yarn install
yarn build
cd ..
go build
```

I'll make sure to update the README before closing the issue.

BTW note that on the infrequent times I do work on the project, I work on the in-progress rust backend, which is far from complete, but aims to replace the mpd dependency.

**Comment by foldfree** [comment]
Thank you! Yes your project looks really neat, simple and fast :)

Thank you for the explanation, I get a better understanding of what is not working.

I am using `ubuntu LTS 22.04.2 x86_64` with `yarn --version 0.32+git`
in `/pickup/react/`, `$ yarn install` gives the following output:

```
00h00m00s 0/0: : Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cliapp/app.py", line 193, in _run
    self.process_args(args)
  File "/usr/bin/yarn", line 157, in process_args
    scenarios, implementations = self.parse_scenarios(args)
  File "/usr/bin/yarn", line 214, in parse_scenarios
    blocks = mdparser.parse_file(filename)
  File "/usr/lib/python3/dist-packages/yarnlib/mdparser.py", line 78, in parse_file
    return self.parse_string(text)
  File "/usr/lib/python3/dist-packages/yarnlib/mdparser.py", line 71, in parse_string
    markdown.markdown(text, output=f, extensions=[ext])
  File "/home/cesar/.local/lib/python3.10/site-packages/markdown/core.py", line 386, in markdown
    md = Markdown(**kwargs)
  File "/home/cesar/.local/lib/python3.10/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/home/cesar/.local/lib/python3.10/site-packages/markdown/core.py", line 125, in registerExtensions
    ext.extendMarkdown(self)
TypeError: ParseScenarioTestBlocks.extendMarkdown() missing 1 required positional argument: 'md_globals' 
```

**Comment by werkshy** [comment]
a) If you want to just play with the app, you can grab a pre-built binary from the "CI" action - e.g. https://github.com/werkshy/pickup/actions/runs/5501566578 (I should set up proper Github releases I guess)

b) I'm not sure what 'yarn' command you are running there, but it's written in Python and isn't the node dependency manager I meant. I don't remember how I installed yarn on my Ubuntu 22.04 machine, maybe with `npm install -g yarn`? (You might want to remove the other yarn package to avoid confusion).

**Comment by foldfree** [comment]
Thanks, I found the issue, ubuntu has another package called yarn from their `cmdtest` tools suite that is conflicting with this actual yarn.
see: https://github.com/yarnpkg/yarn/issues/3189
I removed it and installed the npm yarn.
It builds fine now.
